#!/bin/bash

set -e


url='https://discord.com/api/download/stable?platform=linux&format=tar.gz'

if [[ $# -gt 2 ]]; then
    echo 'Too many arguments passed!'
    exit 1
elif [[ $1 == '--version' ]]; then
    if [[ $# -eq 1 ]]; then
        echo 'Missing a version number!'
        exit 1
    fi

    echo "Downloading version $2"

    url="https://stable.dl2.discordapp.net/apps/linux/0.0.$2/discord-0.0.$2.tar.gz"
elif [[ $# -ne 0 ]]; then
    echo 'Extra arguments passed!'
    exit 1
fi

temp_dir=$(mktemp -d)
sudo echo "Creating a temporary directory ($temp_dir)"

echo "Downloading discord-update.tar.gz to $temp_dir"
archive="$temp_dir/discord-update.tar.gz"
wget $url -O $archive

if [[ ! -f $archive ]]; then
    echo 'Downloaded file is missing; exiting'
    sudo rm -r $temp_dir
    exit 1
fi

echo "Unzipping $archive to /opt/Discord..."
sudo tar -xzf $archive -C '/opt'

files=(
    'discord.desktop'
)

for file in ${files[@]}; do
    old_path="/opt/discord/$file"
    new_path="/opt/Discord/$file"
    echo "Moving $old_path to $new_path"

    sudo mv -f $old_path $new_path
done

echo 'Removing old Discord installation...'
sudo rm -r '/opt/discord'

echo 'Renaming /opt/Discord to /opt/discord...'
sudo mv '/opt/Discord' '/opt/discord'

echo 'Removing the temporary directory...'
sudo rm -r $temp_dir


vencord_dir="$(dirname "$(readlink -f "$0")")/vencord"
if [[ -f $vencord_dir ]]; then
    while true; do
        read -rp 'Install Vencord? [Y/n] ' input
        input=${input,,}

        if [[ $input == 'y' || -z $input ]]; then
            $vencord_dir

            break
        elif [[ $input == 'n' ]]; then
            break
        fi
    done
fi


echo "Discord updated."
